# Generated by Django 3.1.2 on 2020-12-02 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_catagory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='vendor',
        ),
    ]
