# Generated by Django 3.1.2 on 2020-11-13 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_auto_20201113_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='customer',
            new_name='user',
        ),
    ]
