# Generated by Django 3.1.2 on 2020-11-16 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0011_catagory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Catagory',
        ),
    ]
