# Generated by Django 3.1.2 on 2020-11-17 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0014_remove_order_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderitem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.orderitem'),
        ),
    ]
