# Generated by Django 3.1.2 on 2020-11-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0016_shippingaddress_default_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='pincode',
            field=models.IntegerField(null=True),
        ),
    ]
