# Generated by Django 3.1.2 on 2020-11-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0018_auto_20201119_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='pincode',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
