# Generated by Django 3.1.2 on 2020-11-22 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0022_auto_20201122_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='item_total_price',
        ),
    ]
