# Generated by Django 3.1.2 on 2020-11-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0023_remove_orderitem_item_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
