# Generated by Django 3.1.2 on 2020-11-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0024_orderitem_item_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='create_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
