# Generated by Django 3.1.2 on 2020-11-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0025_auto_20201122_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='complete',
            field=models.IntegerField(choices=[(1, 'Order Not Placed'), (2, 'Order Placed'), (4, 'Order Cancelled')], default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='pyment_status',
            field=models.IntegerField(choices=[(1, 'Not Paid'), (2, 'Payment Pending'), (3, 'Paid')], default=1),
        ),
    ]
