# Generated by Django 3.1.2 on 2020-11-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0026_auto_20201125_0542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='complete',
            new_name='order_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivered',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.IntegerField(choices=[(1, 'Order Accepted'), (2, 'Order Dispatched'), (3, 'Order Delivered'), (4, 'Order Cancelled')], default=1),
        ),
    ]
