# Generated by Django 3.1.2 on 2020-11-25 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0027_auto_20201125_0544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='pyment_status',
            new_name='payment_status',
        ),
    ]
