# Generated by Django 3.1.2 on 2020-11-30 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0028_auto_20201125_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='create_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
