# Generated by Django 3.1.2 on 2020-12-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0029_auto_20201130_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
